apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-site
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/ton-repo/mon-projet.git
    path: k8s/nginx
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
